name: 'Trello integration'

# Move Trello cards when PRs are created, published or merged.
#
# Requires some secrets and/or vars!
# See https://github.com/verkstedt/actions#trello
#
# This file has been created from
# https://github.com/verkstedt/.github/blob/main/workflow-templates/trello.yaml
#
# IF YOU MODIFY IT IN ANY WAY, DESCRIBE IT IN THE COMMENT HERE
# to make updating in the future easier.

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - ready_for_review
      - converted_to_draft

jobs:
  trello:
    name: 'Move trello cards'
    uses: verkstedt/actions/.github/workflows/trello.yaml@v1
    secrets: inherit
